


services:
  - type: web
    name: laravel_app
    plan: free
    runtime: docker
    dockerfilePath: Dockerfile

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false

      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite

      - key: SESSION_DRIVER
        value: file

      - key: LOG_CHANNEL
        value: stderr

      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: "1"
      - key: REAL_IP_HEADER
        value: "1"
      - key: SKIP_COMPOSER
        value: "1"